set nocompatible

source ~/.vim/ui.vim
source ~/.vim/goodies.vim
source ~/.vim/autocommands.vim
source ~/.vim/bundles.vim

" CTags
map <Leader>rt :!ctags --extra=+f -R *<CR><CR>
set tags=tmp/tags;/,./tmp/tags;/,tags;/,./tags;/

" NERDTree and Tagbar toogle
nmap <leader>n :call ToggleNERDTreeAndTagbar()<CR>

" Don't close NERDTree when opening a file
let NERDTreeQuitOnOpen=0

if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

" Great colors
set t_Co=256
