set nocompatible

source ~/.vim/ui.vim
source ~/.vim/goodies.vim
source ~/.vim/autocommands.vim
source ~/.vim/bundles.vim

" CTags
map <Leader>rt :!ctags --extra=+f -R *<CR><CR>
set tags=tmp/tags;/,./tmp/tags;/,tags;/,./tags;/

" NERDTree and Tagbar toogle
nmap <leader>n :call ToggleNERDTreeAndTagbar()<CR>

if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

" Great colors
set t_Co=256

" autoload sesion
let g:session_autoload = "yes"
let g:session_autosave = "no"
